export default {
	products: [
		{
			_id: 123,
			name: 'Slim Shirt',
			slug: 'slim-shirt',
			category: 'Shirts',
			image: '/images/slim-shirt.jpeg',
			price: 6000,
			brand: 'Nike',
			rating: 4.5,
			review_count: 10,
			stock_count: 0,
		},
		{
			_id: 124,
			name: 'Slim Shirt 2',
			slug: 'slim-shirt-2',
			category: 'Shirts',
			image: '/images/slim-shirt.jpeg',
			price: 4000,
			brand: 'Nike',
			rating: 4.2,
			review_count: 8,
			stock_count: 15,
		},
		{
			_id: 125,
			name: 'Slim Shirt 3',
			slug: 'slim-shirt-3',
			category: 'Shirts',
			image: '/images/slim-shirt.jpeg',
			price: 5500,
			brand: 'Adidas',
			rating: 4.8,
			review_count: 2,
			stock_count: 7,
		},
	],
};
